export const ADD_NEW_PRODUCT = "ADD_NEW_PRODUCT";
export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const PRODUCT_LIST_TO_CART = 'PRODUCT_LIST_TO_CART';
export const PRODUCT_REMOVE_TO_CART = 'PRODUCT_REMOVE_TO_CART';
export const INCREASE_QUANTITY = 'INCREASE_QUANTITY';
export const DECREASE_QUANTITY = 'DECREASE_QUANTITY';
export const LOGIN_SESSION = 'LOGIN_SESSION';
export const LOGOUT_USER = 'LOGOUT_USER';
export const GET_USER_DATA = 'GET_USER_DATA';

